/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Insight Questions API
 * API для работы с вопросами для инсайтов
 * OpenAPI spec version: 1.0.0
 */
import type { BaseInsightResultDtoResultType } from './baseInsightResultDtoResultType';
import type { BaseInsightResultDtoResultInt } from './baseInsightResultDtoResultInt';
import type { BaseInsightResultDtoResultVariants } from './baseInsightResultDtoResultVariants';

export interface BaseInsightResultDto {
  /** Идентификатор результата */
  id: string;
  /** Тип результата */
  result_type: BaseInsightResultDtoResultType;
  /** Числовой результат */
  result_int?: BaseInsightResultDtoResultInt;
  /** Список строковых результатов */
  result_variants?: BaseInsightResultDtoResultVariants;
  /** Идентификатор вопроса */
  insight_question_id: string;
  /** Идентификатор ответа на опрос */
  survey_response_id: string;
}
