/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Insight Questions API
 * API для работы с вопросами для инсайтов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Тип результата
 */
export type BaseInsightResultDtoResultType =
  (typeof BaseInsightResultDtoResultType)[keyof typeof BaseInsightResultDtoResultType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BaseInsightResultDtoResultType = {
  int: 'int',
  variants_multiple: 'variants_multiple',
} as const;
