/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Insight Questions API
 * API для работы с вопросами для инсайтов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Статус инсайта
 */
export type BaseSurveyResponseDtoInsightStatus =
  (typeof BaseSurveyResponseDtoInsightStatus)[keyof typeof BaseSurveyResponseDtoInsightStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BaseSurveyResponseDtoInsightStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
} as const;
