/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Insight Questions API
 * API для работы с вопросами для инсайтов
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSurveyResponseDto {
  /** Идентификаторы вопросов для инсайта */
  insight_question_ids: string[];
  /** Ответ на опрос */
  response: string;
}
