/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Insight Questions API
 * API для работы с вопросами для инсайтов
 * OpenAPI spec version: 1.0.0
 */
import type { CreateInsightQuestionDtoResponseType } from './createInsightQuestionDtoResponseType';
import type { CreateInsightQuestionDtoResponseVariants } from './createInsightQuestionDtoResponseVariants';

export interface CreateInsightQuestionDto {
  /**
   * Краткий заголовок вопроса, отражающий его суть
   * @minLength 3
   * @maxLength 200
   */
  title: string;
  /**
   * Полный текст вопроса, который будет использоваться для анализа
   * @minLength 10
   * @maxLength 1000
   */
  prompt: string;
  /** Тип ожидаемого ответа: 'int' - числовой ответ, 'variants_multiple' - выбор из нескольких вариантов */
  response_type: CreateInsightQuestionDtoResponseType;
  /** Список возможных вариантов ответа. Обязательно для response_type='variants_multiple', иначе должно быть null */
  response_variants?: CreateInsightQuestionDtoResponseVariants;
  /** Идентификатор модели LLM, которая будет использоваться для обработки вопроса (например, 'gpt-3.5-turbo', 'gpt-4') */
  llm_model: string;
  /**
   * Параметр температуры для LLM модели (от 0 до 1). Влияет на креативность ответов: 0 - более консервативные, 1 - более творческие
   * @minimum 0
   * @maximum 1
   */
  llm_temperature: number;
}
