/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Insight Questions API
 * API для работы с вопросами для инсайтов
 * OpenAPI spec version: 1.0.0
 */

/**
 * Список возможных вариантов ответа. Обязательно для response_type='variants_multiple', иначе должно быть null
 */
export type UpdateInsightQuestionDtoResponseVariants = string[] | null;
